[project]
name = "clif_risk-tools_oncology"
r_version = ">= 4.6.0"

[dependencies]
arrow = "*"
base64enc = "*"
collapse = "*"
comorbidity = "*"
"data.table" = "*"
dplyr = "*"
fst = "*"
ggplot2 = "*"
here = "*"
htmltools = "*"
janitor = "*"
lubridate = "*"
pROC = "*"
ps = "*"
readxl = "*"
rlang = "*"
stringr = "*"
tibble = "*"
tidyr = "*"
tidytable = "*"
yaml = "*"
